name: Validate Gradle Wrapper

on: [ push, pull_request, workflow_dispatch ]

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        uses: gradle/wrapper-validation-action@v1
