name: Submit GitHub Dependency Graph
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-and-submit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        develocity-access-key: ${{ secrets.GE_SOLUTIONS_ACCESS_TOKEN }}
        dependency-graph: generate-and-submit
    - name: Run gradle to resolve dependencies
      run: ./gradlew :ForceDependencyResolutionPlugin_resolveAllDependencies
